[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"

fs_permissions = [
  { access = "read", path = "./test/data"},
  { access = "write", path = "./tmp"},
]

[fmt]
line_length = 100

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
